#!/usr/bin/php -q
<?php
/*
 * erstellt / holt die zum Semster passende parent cat
 * Die cat wird angelegt abhänig von der in der config definierten TOPPARENTID passend zum aktuellen Semester
 * Copyright (C) 2021-2022 Tim-Florian Reinartz
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

// config file einbinden
// config liegt z.b. einen Ordner drüber
// require_once ('../config.inc.php');

// cat zu semester erstellen anfang
/* Lese Parameter */
if (isset($_GET["jahr"]) && isset($_GET["semester"])) {
    $termYear = urlencode($_GET["jahr"]);
    $termYear = (string) htmlspecialchars($termYear);
    $termYear = Util::replaceSpace($termYear);
    $termTypeId = urlencode($_GET["semester"]);
    $termTypeId = (string) htmlspecialchars($termTypeId);
    $termTypeId = Util::replaceSpace($termTypeId);
    // SS und WS gehen auch als Werte Umwandlung in 30 bzw. 31
    //dies kann an einer anderen Uni anders sein, an der BUW war dies 30 und 31 
    if ($termTypeId == "SS") {
        $termTypeId = TERMTYPEID_SOSE;
    } elseif ($termTypeId == "WS") {
        $termTypeId = TERMTYPEID_WISE;
    }
} else {
    // aus config, damit wird wenn nichts angegeben das aktuelle Semster und Jahr genutzt
    if (in_array($monat, $sose)) {
        $termTypeId = TERMTYPEID_SOSE;
        $termYear = $jahr;
    } else {
        $termTypeId = TERMTYPEID_WISE;
        if ($monat == 1 || $monat == 2 || $monat == 3) {
            $termYear = $jahr - 1;
        } else {
            $termYear = $jahr;
        }
    }
}

if ($termTypeId == 30) {
    $catname = "Sommersemester " . $termYear;
} elseif ($termTypeId == 31) {
    $jearplus1 = $termYear + 1;
    $catname = "Wintersemster " . $termYear . "/" . $jearplus1;
}
// cat zu semester erstellen ende

// neues Objekt erzeugen
$curl = new curl();

// Beispiel Datensatz aus durch Prototyp Datei erzeugter Rest-API
// Einträge aus der Rest Schnittstelle vom Server im Moment 1
$serverurl = "https://XYZ.uni-wuppertal.de/moodle/index.php?page=1&semester=" . $termTypeId . "&jahr=" . $termYear . "";
//oder als Konstante in config festlegen

// Abfrage der Schnittstelle
$resp = $curl->post($serverurl);

// Decode JSON
// array
$data = json_decode($resp, true);
// object

// zahl am ende entfernen !!!!
$entrycount = array_pop($data);

$catname2 = urlencode($catname);

// Wert vom obersten parent aus config holen ist später meist die mit der id 0
$parent = TOPPARENTID;

// gibt es die cat schon wenn ja kommt eine id zurück die ungleich 0 ist
$serverurlnotinloop = URLFORCURL . "work/moodle-detail-cat-parent.php?name=";
$filterpartcatnozinloop1 = "&parent=";
$callcatnotinloop = $parent;

// URL zusammensetzen
$filterpartcatnotinloop = $filterpartcatnozinloop1 . $callcatnotinloop;
$doitnotinloop = $serverurlnotinloop . $catname2 . $filterpartcatnotinloop;
$urlcatnotinloop = html_entity_decode($doitnotinloop);

$catid = $curl->post($urlcatnotinloop);

// cat anlegen wenn noch nicht vorhanden anfang
if ($catid == 0) {
    // name und parent wird benötigt
    // parent wird durch die fakultät vorgegeben, für den anfang einen festen Wert annehmen
    $serverurl4 = URLFORCURL . "work/moodle-create-cat.php?name=";
    $filterpartcreatecat1 = "&parent=";
    // Wert vom obersten parent aus config holen den rest nach und nach einfügen
    // zum testen
    $parent = TOPPARENTID;
    $callcat1 = $parent;

    // URL zusammensetzen
    $filterpartcreatecat = $filterpartcreatecat1 . $callcat1;

    $doit4 = $serverurl4 . $catname2 . $filterpartcreatecat;

    $url4 = html_entity_decode($doit4);
    $resp4 = $curl->post($url4);

    $newcatid = $resp4;
}
// cat anlegen wenn noch nicht vorhanden ende

$catidmain = 0;

// initialisierung auf 0
$terminate_run = 0;

if ($catid != 0) {
    $catidmain = $catid;
} elseif ($newcatid != 0) {
    $catidmain = $newcatid;
} else {
    $msg = "catid und newcatid sind 0";
    $terminate_run = 1;
}

// wenn es noch keine Daten gibt auf 0 setzen
if (empty($entrycount)) {
    $entrycount = 0;
    $msg = "entrycount ist 0";
}

// in datei schreiben um laufzeit zu spaaren
// für php catid / newcat id jenachdem was gesetzt ist
// code für datei schreiben
$codeforfile = '<?php
/*
* autogenerated file for catid
*
* letzte Änderung ' . date('d.m.Y') . ' (Script!)
* Erstellung
*/
    
';
$codeforfile .= '$catnamemain = "' . "$catname" . '";' . "\n\n";
$codeforfile .= '$catidmain = ' . "$catidmain" . ';' . "\n\n";
$codeforfile .= '$entrycountsemester = ' . "$entrycount" . ';' . "\n\n";
// Achtung: abbrechen wenn cat nicht bestimmt werden konnte
// die fest in datei schreiben bis bei einem nächsten durchlauf wieder okay
// lieber einmal nicht laufen als falsche Einträge vorzunehmen!
if ($terminate_run == 1) {
    $codeforfile .= 'die();' . "\n\n";
}
$codeforfile .= "\n?>"; // /php file

$myfile = fopen("maincat.php", "w") or die("Unable to open file!");
fwrite($myfile, $codeforfile);
fclose($myfile);

// einmal für die bash den entrycount
$myfile2 = fopen("entrycount.txt", "w") or die("Unable to open file!");
$codeforfile2 = 'ENTRYCOUNT=';
$codeforfile2 .= $entrycount;
fwrite($myfile2, $codeforfile2);
fclose($myfile2);

?>